<?php
class Animal
{
   public $food;
   public $location;
   function makeNoiseEat($food)
   {
        echo "Animal eat $food <br>";
   }
   function makeNoiseSleep($location)
   {
       echo "Animal sleep $location <br>";
   }
}

class Cat extends Animal
{
    public $name;

    function makeNoiseEat($name, $food)
    {
        parent::makeNoiseEat($food); // TODO: Change the autogenerated stub
        echo "$name eat $food<br>";
    }
    function makeNoiseSleep($location, $name)
    {
        parent::makeNoiseSleep($location); // TODO: Change the autogenerated stub
        echo "$name sleep $location<br>";
    }
}
class Dog extends Animal
{
    public $name;

    function makeNoiseEat($name, $food)
    {
        parent::makeNoiseEat($food); // TODO: Change the autogenerated stub
        echo "$name eat $food<br>";
    }
    function makeNoiseSleep($location, $name)
    {
        parent::makeNoiseSleep($location); // TODO: Change the autogenerated stub
        echo "$name sleep $location<br>";
    }
}
class Horse extends Animal
{
    public $name;

    function makeNoiseEat($name, $food)
    {
        parent::makeNoiseEat($food); // TODO: Change the autogenerated stub
        echo "$name eat $food<br>";
    }
    function makeNoiseSleep($location, $name)
    {
        parent::makeNoiseSleep($location); // TODO: Change the autogenerated stub
        echo "$name sleep $location<br>";
    }
}
$tommy=new Cat(meet, at_home);